### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by jonpreecems** [pfitzpaddy/angular-count-to#3]
Can we please publish this fantastic package to NPM as well as Bower? Thanks.

**Comment by pfitzpaddy** [comment]
Hi @jonpreecems, now registered as NPM package "angular-filter-count-to". Note that the directive "countTo" has now been updated to "ngCountTo"

i.e. `angular.module('myApp', ['ngCountTo'])` etc
 - please review the readme and feel free to raise further issues.

**Comment by pfitzpaddy** [comment]
`npm install angular-filter-count-to`

**Comment by jonpreecems** [comment]
You're a legend... thank you
