### ISSUE TITLE
countTo is undefined

### ISSUE THREAD

**Issue by jonpreecems** [pfitzpaddy/angular-count-to#4]
Looks like a variable has been missed when directive was renamed from countTo to ngCountTo

`e.textContent = scope.filter ? $filter(scope.filter)(ngCountTo, scope.params, scope.fractionSize) : Math.round(countTo);`

Gives error; 

> ReferenceError: countTo is not defined

**Comment by pfitzpaddy** [comment]
Thanks for the pull request and notification. The updates are now available via npm @0.0.9

**Comment by jonpreecems** [comment]
Thanks for the speedy update
